# Generated by Django 6.0.5 on 2026-05-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultivoCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='csv/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('anio_prediccion', models.IntegerField()),
                ('rendimiento_predicho', models.FloatField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
