# Generated by Django 6.0.5 on 2026-05-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('hectareas', models.FloatField()),
                ('cultivo_principal', models.CharField(max_length=100)),
                ('rendimiento_principal', models.FloatField()),
                ('nivel_principal', models.CharField(max_length=20)),
                ('produccion_principal', models.FloatField()),
                ('cultivo_alternativo', models.CharField(blank=True, max_length=100, null=True)),
                ('rendimiento_alternativo', models.FloatField(blank=True, null=True)),
                ('nivel_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('produccion_alternativa', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivocsv')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
